services:
  nginx:
    image: nginx:latest
    ports:
      - "${DEV_DEPLOY_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DEV_DATABASE_NAME}
      POSTGRES_USER: ${DEV_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: amang-backend
    build:
      context: ./backend
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.development
      DJANGO_SUPERUSER_EMAIL: ${DEV_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DEV_SUPERUSER_PASSWORD}
      ALLOWED_HOSTS: "*"
      DATABASE_URL: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DEV_DATABASE_NAME}
      DATABASE_USER: ${DEV_DATABASE_USER}
      DATABASE_PASSWORD: ${DEV_DATABASE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py create_superuser &&
        python manage.py seed_sessions &&
        python manage.py seed_generations &&
        python manage.py runserver 0.0.0.0:8000
      "

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${DEV_MINIO_API_PORT}:9000"     # API 포트
      - "${DEV_MINIO_CONSOLE_PORT}:9001" # 웹 콘솔 포트
    environment:
      MINIO_ROOT_USER: ${DEV_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${DEV_MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  createbuckets:
    image: minio/mc
    container_name: minio_createbuckets
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${DEV_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${DEV_MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 $${DEV_MINIO_ROOT_USER} $${DEV_MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --ignore-existing myminio/media;
      /usr/bin/mc mb --ignore-existing myminio/static;
      /usr/bin/mc policy set public myminio/media;
      /usr/bin/mc policy set public myminio/static;
      exit 0;
      "

volumes:
  db-data:
  minio_data: