services:
  nginx:
    image: nginx:latest
    ports:
      - "${PROD_DEPLOY_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - backend

  db:
    image: postgres:latest
    ports:
      - "${PROD_DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${PROD_DATABASE_NAME}
      POSTGRES_USER: ${PROD_DATABASE_USER}
      POSTGRES_PASSWORD: ${PROD_DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DEV_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: amang-backend
    build:
      context: ./backend
    environment:
      DJANGO_SETTINGS_MODULE: main.settings.production
      DJANGO_SUPERUSER_EMAIL: ${PROD_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${PROD_SUPERUSER_PASSWORD}
      ALLOWED_HOSTS: ${PROD_ALLOWED_HOSTS}
      DATABASE_URL: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${PROD_DATABASE_NAME}
      DATABASE_USER: ${PROD_DATABASE_USER}
      DATABASE_PASSWORD: ${PROD_DATABASE_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py create_superuser &&
        python manage.py seed_sessions &&
        python manage.py seed_generations &&
        python manage.py runserver 0.0.0.0:8000
      "
  # TODO: add minio service
volumes:
  db-data: