services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/certificate.crt:/etc/nginx/certs/certificate.crt
      - ./nginx/certs/private.key:/etc/nginx/certs/private.key
    depends_on:
      # - frontend
      - backend

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./postgres/.env.development
    volumes:
      - db-data:/var/lib/postgresql/data

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - ./frontend/.env.development
  #   depends_on:
  #     - db

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/amang-backend:latest
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env.development
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py create_superuser &&
        python manage.py seed_sessions &&
        python manage.py seed_generations &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db-data:
  # frontend-cache:
  backend-cache: