# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development Server CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-backend:
    name: Build Backend image
    runs-on: ubuntu-latest
    steps:
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        file: ./backend/Dockerfile
        push: true

  run-server:
    name: Run stage server
    runs-on: self-hosted
    needs: [build-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # - name: Load dotenv from secret
      #   run: |
      #     echo "${{ secrets.ENV_DEVELOPMENT }}" > .env
      - name: Check if containers are running
        id: check-container
        run: |
          {
            echo 'stdout<<EOF'
            docker compose --profile deploy ps -q
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Initialize containers
        if: steps.check-container.outputs.stdout == ''
        run: docker compose --profile deploy up -d --no-recreate

      - name: Pull docker images
        run: docker compose --profile update-target pull

      - name: Run docker compose up
        run: |
          docker compose --profile deploy up -d
      - name: Copy Caddyfile into Caddy Container
        run: docker cp ./apps/infra/stage/Caddyfile caddy:/etc/caddy/Caddyfile

      - name: Graceful reload Caddy
        run: docker exec -w /etc/caddy caddy caddy reload

      - name: Remove unused docker storages
        run: docker system prune -a -f --volumes
