name: Deploy to Development Server

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  deploy:
    name: Deploy and Run Development Server
    runs-on: [self-hosted, development]
    environment:
      name: development
      url: https://amang-dev.json-server.win
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Stop existing containers
        run: docker compose -f docker-compose-dev.yml down
        continue-on-error: true

      - name: Build and run Docker images
        run: docker compose -f docker-compose-dev.yml up -d
        env:
          DEV_DEPLOY_PORT: ${{ vars.DEV_DEPLOY_PORT }}
          DEV_DATABASE_NAME: ${{ secrets.DEV_DATABASE_NAME }}
          DEV_DATABASE_USER: ${{ secrets.DEV_DATABASE_USER }}
          DEV_DATABASE_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}
          DEV_SUPERUSER_EMAIL: ${{ secrets.DEV_SUPERUSER_EMAIL }}
          DEV_SUPERUSER_PASSWORD: ${{ secrets.DEV_SUPERUSER_PASSWORD }}

      - name: Verify deployment
        run: |
          echo "Waiting for services to start..."
          sleep 10
          if [ "$(docker ps -q -f name=backend)" ]; then
            echo "✅ backend is running"
          else
            echo "❌ Failed to start backend"
            exit 1
          fi
