name: Deploy to Production Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  deploy:
    name: Deploy and Run Production Server
    runs-on: [self-hosted, production]
    environment:
      name: production
      url: https://amang.json-server.win
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Stop existing containers
        run: docker-compose -f docker-compose.yml down
        continue-on-error: true

      - name: Build and run Docker images
        run: docker-compose -f docker-compose.yml up -d
        env:
          PROD_DEPLOY_PORT: ${{ secrets.PROD_DEPLOY_PORT }}
          PROD_DATABASE_PORT: ${{ secrets.PROD_DATABASE_PORT }}
          PROD_DATABASE_NAME: ${{ secrets.PROD_DATABASE_NAME }}
          PROD_DATABASE_USER: ${{ secrets.PROD_DATABASE_USER }}
          PROD_DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
          PROD_SUPERUSER_EMAIL: ${{ secrets.PROD_SUPERUSER_EMAIL }}
          PROD_SUPERUSER_PASSWORD: ${{ secrets.PROD_SUPERUSER_PASSWORD }}
          PROD_ALLOWED_HOSTS: ${{ secrets.PROD_ALLOWED_HOSTS }}

      - name: Verify deployment
        run: |
          echo "Waiting for services to start..."
          sleep 10
          if [ "$(docker ps -q -f name=backend)" ]; then
            echo "✅ backend is running"
          else
            echo "❌ Failed to start backend"
            exit 1
          fi
