name: CD Stage

on:
  push:
    branches:
      - development

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  deploy:
    name: Deploy and Run Server
    runs-on: self-hosted
    environment:
      name: development
      url: https://amang-dev.json-server.win
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Stop existing containers
        run: docker compose -f docker-compose-dev.yml down
        continue-on-error: true

      - name: Build and run Docker images
        run: docker compose -f docker-compose-dev.yml up -d
        env:
          DEV_DEPLOY_PORT: ${{ vars.DEV_DEPLOY_PORT }}
          DEV_DATABASE_NAME: ${{ secrets.DEV_DATABASE_NAME }}
          DEV_DATABASE_USER: ${{ secrets.DEV_DATABASE_USER }}
          DEV_DATABASE_PASSWORD: ${{ secrets.DEV_DATABASE_PASSWORD }}
          DEV_SUPERUSER_EMAIL: ${{ secrets.DEV_SUPERUSER_EMAIL }}
          DEV_SUPERUSER_PASSWORD: ${{ secrets.DEV_SUPERUSER_PASSWORD }}
